/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useContext } from 'react';
import { useGLTF } from '@react-three/drei';
import { AppContext } from '../context/app-context';

const phoneGLB = `${process.env.NEXT_PUBLIC_BASE_URL}/phone.glb`;

export default function Model(props) {
  const { nodes, materials } = useGLTF(phoneGLB);
  const { phoneRef, setPhoneRef } = useContext(AppContext);
  const localRef = useRef();

  useEffect(() => {
    setPhoneRef(localRef);
  }, []);

  return (
    <group {...props} dispose={null} ref={phoneRef} scale='1.8'>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.93, 1.51, 2.22]}>
        <mesh
          geometry={nodes.mesh_0.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.mesh_0_1.geometry}
          material={materials['Material.001']}
        />
      </group>
    </group>
  );
}

useGLTF.preload(phoneGLB);
